kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
  type: LoadBalancer  
    - port: 8080                               
      targetPort: 80                    
  selector:
    app: mrdevops                    
                   
